modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Zhincore/Create-Trains/issues"
license = "${mod_license}"

[[mods]]
modId = "create"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime
version = "${file.jarVersion}"
displayName = "${mod_name}"
displayURL = "https://github.com/Zhincore/Create-Trains"
logoFile = "icon.png"
#credits=""
authors = "${mod_author}"
description = '''
${mod_description}
'''

[[dependencies.create]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.create]]
modId = "flywheel"
mandatory = true
versionRange = "[1.0.0,2.0)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.create]]
modId = "ponder"
mandatory = true
versionRange = "[0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create]]
modId = "jei"
mandatory = false
versionRange = "[15.19.0,)"
ordering = "NONE"
side = "CLIENT"

# For recipe replacement / compatibility
[[dependencies.create]]
modId = "railways"
mandatory = false
versionRange = "[1.6.11,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.create]]
modId = "bellsandwhistles"
mandatory = false
versionRange = "[0.4.3,)"
ordering = "BEFORE"
side = "BOTH"
